SistInmobiliaria/Controllers/RendicionController.cs
using Inmobiliaria.Core.IRepositories;
using Inmobiliaria.Core.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistInmobiliaria.Controllers
{
    public class RendicionController : Controller
    {
        // GET: RendicionCAB
        private readonly IRendicionCABRepository _IRendicionCABRepository;
        private readonly IRendicionDETRepository _IRendicionDETRepository;
        private readonly IReembolsoRepository _IReembolsoRepository;
        public RendicionController(IRendicionCABRepository IRendicionCABRepository
                                , IRendicionDETRepository IRendicionDETRepository
                                , IReembolsoRepository IReembolsoRepository)
        {
            _IRendicionCABRepository = IRendicionCABRepository;
            _IRendicionDETRepository = IRendicionDETRepository;
            _IReembolsoRepository = IReembolsoRepository;
        }
        public ActionResult Index()
        {

            return View();
        }
        #region CABECERA
        public ActionResult GetAllRendiciones([DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var list = _IRendicionCABRepository.GetAll();
                return Json(list.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                var list = new List<RendicionCABVM>();
                return Json(list.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult InsertRendicion([DataSourceRequest] DataSourceRequest request, RendicionCABVM model)
        {
            try
            {
                var result = _IRendicionCABRepository.Insert(model);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { success = false, errorMessage = e.Message });
            }

        }
        public ActionResult UpdateRendicion([DataSourceRequest] DataSourceRequest request, RendicionCABVM model)
        {
            try
            {
                var result = _IRendicionCABRepository.update(model);
                return Json(model.IdRendicion, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { success = false, errorMessage = e.Message });
            }
        }
        public JsonResult DeleteRendicion([DataSourceRequest] DataSourceRequest request, RendicionCABVM model)
        {
            try
            {
                var result = _IRendicionCABRepository.Delete(model.IdRendicion);
                return Json(new { success = result == 1 ? true : false, errorMessage = "" });
            }
            catch (Exception e)
            {
                return Json(new { success = false, errorMessage = e.Message });
            }
        }
        #endregion CABECERA
        #region DETALLES
        public ActionResult InsertDetalle([DataSourceRequest]DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<RendicionDETVM> detalles)
        {
            foreach (var detalle in detalles)
            {
                _IRendicionDETRepository.Insert(detalle);
            }
            return Json(new[] { detalles }.ToDataSourceResult(request, ModelState), JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateDetalle([DataSourceRequest]DataSourceRequest request,  [Bind(Prefix = "models")]IEnumerable<RendicionDETVM> detalles)
        {
            double reduccion = 0;
            foreach (var detalle in detalles)
            {
                reduccion+=_IRendicionDETRepository.actualizacion(detalle).Value;
            }
            return Json(reduccion, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteDetalle([DataSourceRequest]DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<RendicionDETVM> detalles)
        {
            double reducion= 0;
            foreach (var detalle in detalles)
            {
                reducion+=_IRendicionDETRepository.eliminacion(detalle.REND_Cod).Value;
            }
            return Json(reducion, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetDetallesbyCabecera([DataSourceRequest]DataSourceRequest request, int idRendicion)
        {
            var res = _IRendicionDETRepository.GetAllByCabecera(idRendicion);
            return Json(res.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        #endregion DETALLES
        #region REEMBOLSO
        [HttpPost]
        public ActionResult InsertReembolso()
        {
            try
            {
                ReembolsoVM model = new ReembolsoVM();
                var result = _IReembolsoRepository.Insert(model);
                return Json(new { success = result > -1 ? true : false, errorMessage = "" });
            }
            catch (Exception e)
            {
                return Json(new { success = false, errorMessage = e.Message });
            }

        }
        #endregion
    }
}

SistInmobiliaria/Views/Rendicion/Index.cshtml
@using Inmobiliaria.Core.ViewModels
@{
    ViewBag.Title = "Rendición";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/ViewController/RendicionViewController.js"></script>
<script src="~/Scripts/ViewController/DetalleRendicion.js"></script>
<script>
    var Url = {
                EnviarRendicion: '@Url.Action("InsertReembolso", "Rendicion")'
            };

</script>
<style>

    .mensaje-color {
        margin-top: 0 !important;
    }
</style>
<article>
    <h2 class="title-grid">@ViewBag.Title</h2>
    <br />
    @(Html.Kendo().Grid<RendicionCABVM>()
                        .Name("RendicionGrid")
                        .Columns(columns =>
                        {

                //columns.Bound(p => p.IdRendicion).Title("Codigo");
                //columns.Bound(p => p.FechaCreacionRendicion).Title("Fecha Creacion").Format("{0: dd/MM/yyyy}");
                //columns.Bound(p => p.FechaEnvioRendicion).Title("Fecha Envio").Format("{0: dd/MM/yyyy}");
                //columns.Bound(p => p.REM_FecCon).Title("Fec Contabilización").Format("{0: dd/MM/yyyy}");
                columns.Bound(p => p.FF_CtaCon).Title("División");
                //columns.Command(command =>
                //{
                //    command.Edit().Text(" ").UpdateText("Guardar");
                //    command.Destroy().Text(" ");
                //}).Title("Opciones");
                columns.Template(@<text></text>)
.ClientTemplate("<div class='order'>" +
"#if(!RENC_ENVI_REND||RENC_ENVI_REND==null){#<a class='k-button k-button-icontext k-grid-edit btn-sm'><span class='k-icon k-i-edit'></span>Editar</a>#}#" +
"#if(RENC_ENVI_REND==null){#<a class='k-button k-button-icontext k-grid-cancel btn-sm'><span class='k-icon k-i-cancel'></span>Eliminar</a>#}#" +
"</div>"
)
.Title("OPCIONES").Width(150);
                    })
                    .Scrollable()
                    .ToolBar(toolbar =>
                    {
                        toolbar.Create().Text("Nuevo");
                        toolbar.Excel().Text("Exportar Excel");
                        toolbar.Pdf().Text("Exportar PDF");
                    })
                    .Pageable(pageable => pageable
                    .Refresh(true)
                    .PageSizes(true)
                    .ButtonCount(10)
                    .Messages(m =>
                    {
                        m.Display("Rendicion mostradas {0} - {1} de {2}");
                        m.Empty("No hay Rendiciones");
                        m.ItemsPerPage("Rendicion por página");
                    })
                    )
                    .Excel(e => e.AllPages(true).FileName("Rendicions.xlsx"))
                    .Pdf(e => e.AllPages().FileName("Rendicions.pdf"))
                    .Filterable(filterable => filterable
                    .Extra(false)
                    .Operators(operators => operators
                    .ForString(str => str.Clear()
                    .Contains("Contiene")
                    )
                    .ForNumber(str => str.Clear()
                    .IsEqualTo("Es igual a")
                    )
                    .ForDate(str => str.Clear()
                    .IsGreaterThanOrEqualTo("Desde")
                    .IsLessThanOrEqualTo("Hasta")

                    )
                    )
                    )
                    .Editable(editable =>
                    {
                        editable.Mode(GridEditMode.PopUp).TemplateName("_RendicionEditor").DisplayDeleteConfirmation("¿Está seguro(a) que desea eliminar este Rendicion?");
                    })
                    .DataSource(dataSource => dataSource
                        .Ajax()
                        .PageSize(10)
                        .Model(model => model.Id(p => p.IdRendicion))
                        .Read(read => read.Action("GetAllRendiciones", "Rendicion"))
                        .Create(create => create.Action("InsertRendicion", "Rendicion"))
                        .Update(update => update.Action("UpdateRendicion", "Rendicion"))
                        .Destroy(destroy => destroy.Action("DeleteRendicion", "Rendicion"))
                        .Events(events =>
                            {
                                events.RequestEnd("gridManager.onRequestEnd");
                            })
                    )
                    .Events(events => events
                    .Edit("gridManager.onEdit").Save("gridManager.guardando")
                    )
    )
    <div class="btns-footer">
        <button class="k-button btn-sm" type="button" name="btnGuardar" value="Guardar"
                id="btnGuardar" onclick="gridManager.finalizaAceptacionEntrevista()">
            <span class="k-icon k-i-check space-icons"></span> Finalizar
        </button>
    </div>
</article>